### ISSUE TITLE
SystemLog is double html encoding the log content

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.Logging#28]
Razor automatically html encodes, but the /systemlog view is doing this at present:
`@Html.Encode(item.Message)`
whereas I'd have expected this:
`@item.Message`
resulting in the log page being rather hard to read. For example we see 
`&quot;hello&quot;`   
instead of 
"hello".
Is there a good reason for this?

**Comment by StewartBellamy** [comment]
@CrispinF  - I always end up overriding this view for that sole reason.

**Comment by JimKerslake** [comment]
Implemented as part of commit for #31
